module.exports={
    user:{
        user_login:'user/login',
        user_singup:'user/singup',
        user_logout:'user/logout',
        user_GetRoles:'user/getRoles',
        user_GridUsers:'user/getGridUsers',
        user_OpenUser:'user/openUser',
        user_SaveUser:'user/saveUser'
    },
    common:{
        com_delete:'common/com_delete'
    },
    app:{
         getkeywords:'app/keywords',
         app_gridCustomers:'app/getGridCustomers',
         app_customerSave:'app/customerSave',
         app_openCustomer:'app/openCustomer'
    }
}