module.exports={
    user:{
        user_login:'user/login',
        user_singup:'user/singup',
        user_logout:'user/logout',
        user_GetRoles:'user/getRoles',
        user_GridUsers:'user/getGridUsers',
        user_OpenUser:'user/openUser',
        user_SaveUser:'user/saveUser'
    },
    common:{
        com_delete:'common/com_delete'
    },
    app:{
         getkeywords:'app/keywords',
         app_gridCustomers:'app/getGridCustomers',
         app_customerSave:'app/customerSave',
         app_openCustomer:'app/openCustomer',
         app_gridServices:'app/getGridServices',
         app_serviceSave:'app/serviceSave',
         app_openService:'app/openService',
         app_gridAppointments:'app/getGridAppointments',
         app_openAppointment:'app/openAppointment',
         app_getClientInfo:'app/getClientInfo',
         app_getEmployeeList:'app/getEmployeeList',
         app_getServiceList:'app/getServiceList',
         app_gridAppointmentLists:'app/getGridAppointmentLists',
         app_appointmentListsSave:'app/appointmentListsSave',
         app_appointmentSave:'app/appointmentSave'         
    }
}